#!/usr/bin/env python
# -*- coding: utf-8 -*-

import struct


PACKET_HEADER = '!BBB'
NET_PACKETHEADERSIZE = struct.calcsize(PACKET_HEADER)
NET_MAX_PACKETSIZE = 1400
NET_MAX_PAYLOAD = NET_MAX_PACKETSIZE-6
NET_MAX_CHUNKHEADERSIZE = 3
MAX_SNAPSHOT_PACKSIZE=900

NET_PACKETFLAG_CONTROL=1      #???
NET_PACKETFLAG_CONNLESS=2     #???? Наверное, когда идет подключение
NET_PACKETFLAG_RESEND=4       #хз, видать когда пакет повторно шлется
NET_PACKETFLAG_COMPRESSION=8  #сжатие блеадь

NET_CHUNKFLAG_VITAL = 1
MSGFLAG_VITAL=1


# NETMSG_INVALID=0,
# NETMSGTYPE_SV_MOTD=1
# NETMSGTYPE_SV_CHAT=3 # 100%
NETMSGTYPE_SV_TEAM=44
# NETMSGTYPE_SV_KILLMSG=4 #100500% !!
# #отсюда хз что с цифрами -- не проверено!!
#
# NETMSGTYPE_SV_TUNEPARAMS=6
# NETMSGTYPE_SV_EXTRAPROJECTILE=7 #выстрел. тут всё збс
# NETMSGTYPE_SV_READYTOENTER=8
# NETMSGTYPE_SV_WEAPONPICKUP=9
# NETMSGTYPE_SV_EMOTICON=10
# NETMSGTYPE_SV_VOTECLEAROPTIONS=11
# NETMSGTYPE_SV_VOTEOPTIONLISTADD=12
# NETMSGTYPE_SV_VOTEOPTIONADD=13
# NETMSGTYPE_SV_VOTEOPTIONREMOVE=14
# NETMSGTYPE_SV_VOTESET=15
# NETMSGTYPE_SV_VOTESTATUS=16
NETMSGTYPE_SV_SERVERSETTINGS=175555
NETMSGTYPE_SV_CLIENTINFO=18
NETMSGTYPE_SV_GAMEINFO=19
NETMSGTYPE_SV_CLIENTDROP=2000
NETMSGTYPE_SV_GAMEMSG=21 # эта вроде ок
#
NETMSGTYPE_DE_CLIENTENTER=225555
NETMSGTYPE_DE_CLIENTLEAVE=235555
# NETMSGTYPE_CL_SAY=24
# NETMSGTYPE_CL_SETTEAM=25
# NETMSGTYPE_CL_SETSPECTATORMODE=26
# NETMSGTYPE_CL_STARTINFO=27 #номер 20!! О_о
# NETMSGTYPE_CL_KILL=28
NETMSGTYPE_CL_READYCHANGE=29555
#
# #дальше ОК
# NETMSGTYPE_CL_EMOTICON=30
# NETMSGTYPE_CL_VOTE=31
# NETMSGTYPE_CL_CALLVOTE=32
# NUM_NETMSGTYPES=33




NETMSG_INVALID=0
NETMSGTYPE_SV_MOTD=1
NETMSGTYPE_SV_BROADCAST=2
NETMSGTYPE_SV_CHAT=3
NETMSGTYPE_SV_KILLMSG=4
NETMSGTYPE_SV_SOUNDGLOBAL=5
NETMSGTYPE_SV_TUNEPARAMS=6
NETMSGTYPE_SV_EXTRAPROJECTILE=7
NETMSGTYPE_SV_READYTOENTER=8
NETMSGTYPE_SV_WEAPONPICKUP=9
NETMSGTYPE_SV_EMOTICON=10
NETMSGTYPE_SV_VOTECLEAROPTIONS=11
NETMSGTYPE_SV_VOTEOPTIONLISTADD=12
NETMSGTYPE_SV_VOTEOPTIONADD=13
NETMSGTYPE_SV_VOTEOPTIONREMOVE=14
NETMSGTYPE_SV_VOTESET=15
NETMSGTYPE_SV_VOTESTATUS=16
NETMSGTYPE_CL_SAY=17
NETMSGTYPE_CL_SETTEAM=18
NETMSGTYPE_CL_SETSPECTATORMODE=19
NETMSGTYPE_CL_STARTINFO=20
NETMSGTYPE_CL_CHANGEINFO=21
NETMSGTYPE_CL_KILL=22
NETMSGTYPE_CL_EMOTICON=23
NETMSGTYPE_CL_VOTE=24
NETMSGTYPE_CL_CALLVOTE=25
NUM_NETMSGTYPES=26






TEAM_SPECTATORS = -1
TEAM_RED = 0
TEAM_BLUE = 1
NUM_TEAMS = 2

FLAG_MISSING = -3
FLAG_ATSTAND = -2
FLAG_TAKEN = -1

MAX_CLIENTS = 16 #??????? не проверено!
max_int = 9999999999 #???


WEAPON_HAMMER=0
WEAPON_GUN=1
WEAPON_SHOTGUN=2
WEAPON_GRENADE=3
WEAPON_LASER=4
WEAPON_NINJA=5
NUM_WEAPONS=6

SPEC_FREEVIEW=-1,

GAMEFLAG_TEAMS = 1<<0
GAMEFLAG_FLAGS = 1<<1
GAMEFLAG_SURVIVAL = 1<<2

##msg consts:
DO_CHAT=0
DO_BROADCAST=1
DO_SPECIAL=2

PARA_NONE=0
PARA_I=1
PARA_II=2
PARA_III=3

# struct CGameMsg
# {
# int m_Action;
# int m_ParaType;
# const char *m_pText;
# };

gs_GameMsgList = [
    [DO_CHAT, PARA_NONE, "Teams were swapped"], #*GAMEMSG_TEAM_SWAP*/
    [DO_CHAT, PARA_NONE, "Invalid spectator id used"],	#/*GAMEMSG_SPEC_INVALIDID*/  !
    [DO_CHAT, PARA_NONE, "Teams were shuffled"], #/*GAMEMSG_TEAM_SHUFFLE*/
    [DO_CHAT, PARA_NONE, "Teams have been balanced"], #/*GAMEMSG_TEAM_BALANCE*/
    [DO_SPECIAL, PARA_NONE, ""],  #/*GAMEMSG_CTF_DROP*/ 	#// special - play ctf drop sound
    [DO_SPECIAL, PARA_NONE, ""],  #/*GAMEMSG_CTF_RETURN*/ 	#// special - play ctf return sound

    [DO_SPECIAL, PARA_I, "All players were moved to the %s"], #/*GAMEMSG_TEAM_ALL*/ 	#// special - add team name
    [DO_SPECIAL, PARA_I, "You were moved to %s due to team balancing"],	#/*GAMEMSG_TEAM_BALANCE_VICTIM*/  #// special - add team name
    [DO_SPECIAL, PARA_I, ""],#/*GAMEMSG_CTF_GRAB*/ 	#// special - play ctf grab sound based on team

    [DO_SPECIAL, PARA_III, ""], #/*GAMEMSG_CTF_CAPTURE*/ 	#// special - play ctf capture sound + capture chat message
]

GAMEMSG_TEAM_SWAP=0
GAMEMSG_SPEC_INVALIDID=1
GAMEMSG_TEAM_SHUFFLE=2
GAMEMSG_TEAM_BALANCE=3
GAMEMSG_CTF_DROP=4
GAMEMSG_CTF_RETURN=5
GAMEMSG_TEAM_ALL=6
GAMEMSG_TEAM_BALANCE_VICTIM=7
GAMEMSG_CTF_GRAB=8
GAMEMSG_CTF_CAPTURE=9
NUM_GAMEMSGS=10